deploy:
  true:
    condition: $TOXENV == py27
    repo: bradrf/kubey
    tags: true
  distributions: sdist bdist_wheel
  password:
    secure: slFGqd+qO0CSSLWSs799az3SzosIch9O7/v93yuWLh+Ur/RVJHqAa076SLAUI8lGrWg8rxbr6ChJehAdfCqpLR0UD0m0rUvupHRljIYEUn2nGYbGYydd6qWprglDPgq0pEHHUGtziqI/2CW1dYX0o7fi7Xy0zGTc45ugpDzLEnFkLkTTowjdpGMNx88GVrKwgjaXlY5/OpG9LzSaNxui9+3D2uje8MXZ+4kMRZ+/do38NxrMW9ByWMi9RicHOlGfiY/XWvHT9dBIv93TrJcrbIFff72hPYaEAzqHV969doUqn7O8Sbgd+sVMlv1VYMJqK+Nof8jUMFmWyRS0yMZpW3D0zjsbdNrkme6CFqH59EcoJfsVyz4MNAoED/FjJ/FcNqSsQ1s1ryjKw/Zt6ZfSftJH3eoF5JqnR5LmI/mZunvg9v8b1FQXqAY3VrIqHirNyz1OYoDN4KvaiOobBx1Im6QvsCB3O1fG3FWtL6lW8B+eP2P95vY+oRou/akQ9qHJyvRojKqTlnNfH5daIMovO+hyoIGJo2eYQZtNRI2zydjJIkpuS3D96Vj4BOfApRuuJbpVxBX4eZMcMVkCM71k2w2ejzjC4duIswIIhRarvKGV5PK7ujSKnVK4t7VK+EjN0O3TSAM+Lp8KWQ4IW1stUtxMu7Q5v30SjoLgyJUulMI=
  provider: pypi
  user: bradrf
env:
- TOXENV=py35
- TOXENV=py34
- TOXENV=py33
- TOXENV=py27
- TOXENV=pypy
- TOXENV=flake8
install: pip install -U tox
language: python
python: 3.5
script: tox -e ${TOXENV}
after_success:
  - codeclimate-test-reporter
